### PR TITLE
Include Fonts in Examples

### PR DESCRIPTION
**Pull request by bravomartin**
This PR include the examples' fonts in the function itself to ensure they are embedded on export

### CODE REVIEW

**Comment by fdoflorenzano** [comment]
When exporting the business card type is exported and seen correctly, but for the IG posts: 

https://user-images.githubusercontent.com/13511560/141500639-4412615b-5b47-4d91-b31c-818e9bc38d2b.mov

**Comment by bravomartin** [comment]
that is odd because the code is exactly the same in both.

**Comment by bravomartin** [comment]
I haven't changed a thing, tested and it works as expected. 
Can you give it another try? The right version should have a folder /assets/ with the fonts inside, and a styles.css file with the font-face references.

**Comment by fdoflorenzano** [comment]
Hey! I just did and yeah, it's that set up and I also checked that I yalc-ked correctly. I just did again twice and same thing. Just to clarify, the preview in the tool it self shows the font correctly, it's just the video export the one that isn't showing the typeface.

**Comment by bravomartin** [comment]
@fdoflorenzano try again.

**Review by fdoflorenzano — APPROVED** [review]
There we goooo! Very nice :)

**Pull request merged**
