### PR TITLE
Template dependencies fix

### PR DESCRIPTION
**Pull request by fdoflorenzano**
We had some issues, and still have tbh, running `lerna bootrstrap` and `lerna bootrstrap --hoist`. Some issues arose by the `--hoist` flag, so we removed it from the scripts of the project.

That said, `lerna bootrstrap` sometimes throws a weird error that even seems non-deterministic, so I'm not sure whats happening. If all `node_modules` and `package-lock.json` are deleted, and then run `lerna bootrstrap`, it works fine. Maybe @runemadsen can take a look at the `package.json` to check anything I missed.

### CODE REVIEW

**Comment by runemadsen** [comment]
Thanks @fdoflorenzano. We shouldn't use `file://` in the `package.json` as that will mess up a few things when we publish. Everything worked fine for me with the old `package.json` and `--hoist`, but I can try to start from a fresh repo and see what happens.

@bravomartin @fdoflorenzano Can you put the error you had here, so I know what to look for?

**Comment by fdoflorenzano** [comment]
> Thanks @fdoflorenzano. We shouldn't use `file://` in the `package.json` as that will mess up a few things when we publish. Everything worked fine for me with the old `package.json` and `--hoist`, but I can try to start from a fresh repo and see what happens.
> 
> @bravomartin @fdoflorenzano Can you put the error you had here, so I know what to look for?

Martin and I got a bunch of `Module not found: Error can't resolve 'react'` after running `npm run dev` on `mechanic-template` after running `bootstrap` with `--hoist`.

Alternatively, if I clone again the master branch and try running `lerna bootstrap`, it throws me this error:
```
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /Users/fdoflorenzano/Projects/DSI/debugging/mechanic/packages/mechanic-template/node_modules/.staging/seedrandom-ce014823
npm ERR! dest /Users/fdoflorenzano/Projects/DSI/debugging/mechanic/packages/mechanic-utils/node_modules/seedrandom
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/fdoflorenzano/Projects/DSI/debugging/mechanic/packages/mechanic-template/node_modules/.staging/seedrandom-ce014823' -> '/Users/fdoflorenzano/Projects/DSI/debugging/mechanic/packages/mechanic-utils/node_modules/seedrandom'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Should we always run with `--hoist`? The times I've tried it it overwrites a bunch of my package.json files for the inner packages, and stuff got lost. Maybe I'm missing like a workflow step. How do you do it generally @runemadsen ?

**Comment by runemadsen** [comment]
Thanks for the explanation @fdoflorenzano. I will take a look at this some point this week.

In general, we should use the correct package names instead of `file://` in the individual `package.json` and then run `lerna bootstrap` to make symlinks to the neighbouring packages. I'm not sure about `--hoist`, but let me look into that. More soon!

**Comment by bravomartin** [comment]
these are the errors I got after running `npm run bootstrap` (which executed `lerna boostrap --hoist` in the root, and running `npm run dev` in `mechanic-template`

The issues were gone after I deleted `node_modules`, `package-lock.json` and ran `npx lerna bootstrap`. not sure if it would have been fixed if i just deleted the node_modules.

image

**Comment by fdoflorenzano** [comment]
I think I finally go it 😄  It works for me using hoisting an on new clones.

**Pull request merged**
